version: "2"
run:
  concurrency: 4
  modules-download-mode: vendor
  issues-exit-code: 1
  tests: true
linters:
  default: all
  disable:
    - cyclop
    - dupl
    - err113
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - gomoddirectives
    - mnd
    - nestif
    - prealloc
    - testpackage
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    dogsled:
      max-blank-identifiers: 3
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocognit:
      min-complexity: 40
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - sloppyReassign
        - elseif
        - unslice
        - wrapperFunc
        - unnamedResult
        - dupImport
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 20
    lll:
      line-length: 180
      tab-width: 1
    misspell:
      locale: US
      ignore-rules:
        - someword
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 7
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/csi-addons/volume-replication-operator
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
